# Generated by Django 2.0.2 on 2018-02-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20180220_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('oval', 'Oval')], default='rectangle', max_length=50, verbose_name='Table shape'),
        ),
    ]
