# Generated by Django 2.0.2 on 2018-02-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20180220_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='second_name',
        ),
    ]
